### ISSUE TITLE
Dúvida de utilização

### ISSUE THREAD

**Issue by samhk222** [thiagogomesverissimo/symfony_base4localuser#1]
Fala Thiago, cara show de bola, comecei a estudar symfony semana passada e estou apaixonado por ele. Utilizarei seu sistema de login, que foi o mais simples que encontrei até agora, como base para meus futuros projetos.

Como iniciei meu projeto agora, estou com um dúvida que é até simples (creio eu). Como faço para proteger algumas rotas, e liberar outras ?

Vou fazer 1 api, e tem a parte pública dela (methodos get para consulta que realmente serão publicas) e methodos que serão protegidos. Queria saber como fazer esse check, sendo que não encontrei  referência nem no /templates/user nem no src/Controller

Poderia me dar 1 help, ai eu até faço um PR pra atualizar a documentação.

Abraços!

**Comment by samhk222** [comment]
Opa, estou vendo lá, as rotas estão no /config/security.yaml confere ?
É porque no vscode não tinha refresheado esse diretório ainda =(

**Comment by thiagogomesverissimo** [comment]
Opa @samhk222 , 

Tem dois jeitos:
 - Um que você citou, usando security.yaml 
 - E outro no controller, exemplo da doc:

```
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
/**
 * @Security("has_role('ROLE_ADMIN')")
 */
public function hello($name)
{
    // ...
}
```
