### ISSUE TITLE
How to resolve permission error?

### ISSUE THREAD

**Issue by zesanriky** [thiagogomesverissimo/symfony_base4localuser#4]
I am running a command 

    php bin/console doctrine:migrations:migrate

Getting the errors below:
`In AbstractMySQLDriver.php line 112:`
                                                                               
    An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied 
    for user 'master'@'localhost' (using password: YES)                               
                                                                               
    In PDOConnection.php line 50:
                                                                               
    SQLSTATE[HY000] [1045] Access denied for user 
    'master'@'localhost'(using 
     password: YES)                                                                
                                                                               
    In PDOConnection.php line 46:
                                                                               
    SQLSTATE[HY000] [1045] Access denied for user 'master'@'localhost' 
    (using password: YES) `

I am using env file below:

    https://github.com/thiagogomesverissimo/symfony_traditional_login/blob/master/.env.dist 
    ` DATABASE_URL=mysql://db_username:db_password@127.0.0.1:3306/db_mydbname`
   
Another try was
`DATABASE_URL=mysql://root:root@localhost/mydbname`
    
I am just replacing the username, password, and mydbname with my information. But still getting the same error. Any help would be highly appreciated.

**Comment by thiagogomesverissimo** [comment]
Your database credentials is not correct:

`Access denied for user 'master'@'localhost' `
